### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by awvwgk** [jla-gardner/data2objects#1]
This project doesn't seem to have a license file, since it is a dependency of graph-pes it would be great to have a compatible open-source license for this project as well.

**Comment by jla-gardner** [comment]
Thanks Sebastian! Added 😄

**Comment by awvwgk** [comment]
Could you also release a version with the LICENSE file shipped in the sdist?

**Comment by jla-gardner** [comment]
Please see `v0.1.0`, available from [PyPI](https://pypi.org/project/data2objects/) and [GitHub](https://github.com/jla-gardner/data2objects/releases/tag/0.1.0)

**Comment by awvwgk** [comment]
Thanks
